# Generated by Django 4.2.1 on 2024-01-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('pubkey', models.CharField(max_length=200)),
                ('lanip', models.CharField(max_length=200)),
                ('wanip', models.CharField(max_length=200)),
                ('wgip', models.CharField(max_length=200)),
                ('wgport', models.CharField(max_length=200)),
                ('nwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='sync.nwork')),
            ],
        ),
    ]
